# Generated by Django 3.2.25 on 2024-09-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_remove_cart_book_cart_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(default=True, upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
